
package pos.openbills;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServerComite", targetNamespace = "http://server.SOAP.openBill.pos.ads/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerComite {


    /**
     * 
     * @param ano
     * @return
     *     returns java.util.List<pos.openbills.MediaComite>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mediaDespesaComite", targetNamespace = "http://server.SOAP.openBill.pos.ads/", className = "pos.openbills.MediaDespesaComite")
    @ResponseWrapper(localName = "mediaDespesaComiteResponse", targetNamespace = "http://server.SOAP.openBill.pos.ads/", className = "pos.openbills.MediaDespesaComiteResponse")
    public List<MediaComite> mediaDespesaComite(
        @WebParam(name = "ano", targetNamespace = "")
        int ano);

    /**
     * 
     * @param ano
     * @return
     *     returns java.util.List<pos.openbills.MediaEstado>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "despesas", targetNamespace = "http://server.SOAP.openBill.pos.ads/", className = "pos.openbills.Despesas")
    @ResponseWrapper(localName = "despesasResponse", targetNamespace = "http://server.SOAP.openBill.pos.ads/", className = "pos.openbills.DespesasResponse")
    public List<MediaEstado> despesas(
        @WebParam(name = "ano", targetNamespace = "")
        int ano);

    /**
     * 
     * @param ano
     * @return
     *     returns java.util.List<pos.openbills.ReceitaComiteValorOrgaos>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "orgaosEstado", targetNamespace = "http://server.SOAP.openBill.pos.ads/", className = "pos.openbills.OrgaosEstado")
    @ResponseWrapper(localName = "orgaosEstadoResponse", targetNamespace = "http://server.SOAP.openBill.pos.ads/", className = "pos.openbills.OrgaosEstadoResponse")
    public List<ReceitaComiteValorOrgaos> orgaosEstado(
        @WebParam(name = "ano", targetNamespace = "")
        int ano);

}
