
package pos.openbills;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServerCandidato", targetNamespace = "http://server.SOAP.openBill.pos.ads/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerCandidato {


    /**
     * 
     * @param ano
     * @return
     *     returns java.util.List<pos.openbills.ReceitaComiteValor>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "despesas", targetNamespace = "http://server.SOAP.openBill.pos.ads/", className = "pos.openbills.Despesas")
    @ResponseWrapper(localName = "despesasResponse", targetNamespace = "http://server.SOAP.openBill.pos.ads/", className = "pos.openbills.DespesasResponse")
    public List<ReceitaComiteValor> despesas(
        @WebParam(name = "ano", targetNamespace = "")
        int ano);

    /**
     * 
     * @param ano
     * @return
     *     returns java.util.List<pos.openbills.QuantidadeDespesaCandidato>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "quantidade", targetNamespace = "http://server.SOAP.openBill.pos.ads/", className = "pos.openbills.Quantidade")
    @ResponseWrapper(localName = "quantidadeResponse", targetNamespace = "http://server.SOAP.openBill.pos.ads/", className = "pos.openbills.QuantidadeResponse")
    public List<QuantidadeDespesaCandidato> quantidade(
        @WebParam(name = "ano", targetNamespace = "")
        int ano);

}
