
package pos.openbills;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServerComiteService", targetNamespace = "http://server.SOAP.openBill.pos.ads/", wsdlLocation = "http://localhost:8080/ads-pos-openBills-SOAP/ServerComiteService?WSDL")
public class ServerComiteService
    extends Service
{

    private final static URL SERVERCOMITESERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERCOMITESERVICE_EXCEPTION;
    private final static QName SERVERCOMITESERVICE_QNAME = new QName("http://server.SOAP.openBill.pos.ads/", "ServerComiteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ads-pos-openBills-SOAP/ServerComiteService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERCOMITESERVICE_WSDL_LOCATION = url;
        SERVERCOMITESERVICE_EXCEPTION = e;
    }

    public ServerComiteService() {
        super(__getWsdlLocation(), SERVERCOMITESERVICE_QNAME);
    }

    public ServerComiteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ServerComite
     */
    @WebEndpoint(name = "ServerComitePort")
    public ServerComite getServerComitePort() {
        return super.getPort(new QName("http://server.SOAP.openBill.pos.ads/", "ServerComitePort"), ServerComite.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerComite
     */
    @WebEndpoint(name = "ServerComitePort")
    public ServerComite getServerComitePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.SOAP.openBill.pos.ads/", "ServerComitePort"), ServerComite.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERCOMITESERVICE_EXCEPTION!= null) {
            throw SERVERCOMITESERVICE_EXCEPTION;
        }
        return SERVERCOMITESERVICE_WSDL_LOCATION;
    }

}
